### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by PacoBell** [SteffanDonal/BeatSaber-TiltFive#2]
"Make sure fpfc is set in Beat Saber's launch options."

Where do I edit these launch options, exactly? Are you referring to the boot.config file in "Beat Saber_Data"?

**Comment by SteffanDonal** [comment]
It's set in your Steam library!
Right click the game, properties, and you'll see launch options in the dialog.

**Comment by PacoBell** [comment]
Okay, I got it in there, but I'm still not seeing an image in T5. What did I do wrong?

**Comment by SteffanDonal** [comment]
Have you got the game setup for modding? (IE. You've run Mod assistant?)

If so, please go into your logs directory and share your "latest" one here, I'll take a look

**Comment by PacoBell** [comment]
There we go. Installed ModAssistant and the core mods and it's all working now. This is gonna be awesome at the office Christmas party 😂

**Comment by SteffanDonal** [comment]
Sweet! Glad to hear it. Take pictures!
